set(_CATKIN_CURRENT_PACKAGE "GUI_Control")
set(GUI_Control_VERSION "0.1.0")
set(GUI_Control_MAINTAINER "smj <smj@gmail.com>")
set(GUI_Control_PACKAGE_FORMAT "1")
set(GUI_Control_BUILD_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(GUI_Control_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(GUI_Control_BUILDTOOL_DEPENDS "catkin")
set(GUI_Control_BUILDTOOL_EXPORT_DEPENDS )
set(GUI_Control_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(GUI_Control_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(GUI_Control_TEST_DEPENDS )
set(GUI_Control_DOC_DEPENDS )
set(GUI_Control_DEPRECATED "")