// Generated by gencpp from file can_test_02/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CAN_TEST_02_MESSAGE_ADDTWOINTS_H
#define CAN_TEST_02_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <can_test_02/AddTwoIntsRequest.h>
#include <can_test_02/AddTwoIntsResponse.h>


namespace can_test_02
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace can_test_02


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::can_test_02::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::can_test_02::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::can_test_02::AddTwoInts > {
  static const char* value()
  {
    return "can_test_02/AddTwoInts";
  }

  static const char* value(const ::can_test_02::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::can_test_02::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::can_test_02::AddTwoInts > 
template<>
struct MD5Sum< ::can_test_02::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::can_test_02::AddTwoInts >::value();
  }
  static const char* value(const ::can_test_02::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_test_02::AddTwoIntsRequest> should match 
// service_traits::DataType< ::can_test_02::AddTwoInts > 
template<>
struct DataType< ::can_test_02::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::can_test_02::AddTwoInts >::value();
  }
  static const char* value(const ::can_test_02::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::can_test_02::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::can_test_02::AddTwoInts > 
template<>
struct MD5Sum< ::can_test_02::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::can_test_02::AddTwoInts >::value();
  }
  static const char* value(const ::can_test_02::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_test_02::AddTwoIntsResponse> should match 
// service_traits::DataType< ::can_test_02::AddTwoInts > 
template<>
struct DataType< ::can_test_02::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::can_test_02::AddTwoInts >::value();
  }
  static const char* value(const ::can_test_02::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAN_TEST_02_MESSAGE_ADDTWOINTS_H
